language: r
sudo: required
cache: packages

before_script:
  - chmod +x ./scripts/cibuild

install:
  - R -e 'install.packages(c("rmarkdown", "xaringan", "callr"))'

script:
  - scripts/cibuild

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
